config/routes.rb
Rails.application.routes.draw do
  localized do
    devise_for :users, :skip => [:registrations]

    as :user do
      get 'users/edit' => 'devise/registrations#edit', :as => :edit_user_registration
      put 'users/:id' => 'devise/registrations#update', :as => :user_registration
    end

    root to: "static_pages#home"

    get '/courses' => 'programs#index', as: :courses
    get '/courses/beginner-bootcamp' => 'programs#level_one', as: :courses_beginner_bootcamp
    get '/courses/intermediate-bootcamp' => 'programs#level_two', as: :courses_intermediate_bootcamp
    get '/courses/advanced-bootcamp' => 'programs#level_three', as: :courses_advanced_bootcamp
    get '/courses/frontend-bootcamp' => 'programs#frontend_bootcamp', as: :courses_frontend_bootcamp

    get '/enroll' => 'orders#new', as: :enroll
    get '/order/:id' => 'orders#show', as: :order
    get '/team' => 'static_pages#team', as: :team
    get '/contact' => 'static_pages#contact', as: :contact
    get '/newsletter' => 'static_pages#newsletter', as: :newsletter

    get '/code-of-conduct' => 'pages#show', id: 'code-of-conduct', as: :code_of_conduct
    get '/terms-and-conditions' => 'pages#show', id: 'terms-conditions', as: :terms_and_conditions
    get '/cancellation-policy' => 'pages#show', id: 'cancellation-policy', as: :cancellation_policy
    get '/faq' => 'pages#show', id: 'faq', as: :faq

    get '/open-evening' => 'static_pages#open_evening', as: :open_evening

    get '/students/:id/qr-code' => 'students#qr_code'
    get '/students/:id/check' => 'students#check_qr_code'

    get '/styleguide' => 'static_pages#styleguide'

    resources :scholarships, only: [:create] do
      collection do
        get :apply
        get :thanks
        get :redirect
      end
    end

    resources :blog, controller: 'posts', only: [:index, :show]
    resources :pages, only: [:show]
    resources :sponsors, only: [:index, :new, :create] do
      member do
        get :thanks
      end

      collection do
        get :plans
      end
    end

    resources :speakers, only: [:index, :new, :create] do
      member do
        get :thanks
      end
    end

    resources :enroll, controller: 'orders', only: [:create, :show] do
      collection do
        post :webhook
      end

      member do
        get :thanks
        post :stripe_webhook
        patch :stripe_token
      end
    end

    get '/sitemap.:format' => 'application#sitemap', constraints: { format: :xml }, as: :sitemap
  end

  namespace :admin do
    get '/' => 'admin#dashboard', as: :root

    require 'sidekiq/web'
    authenticate :user do
      mount Sidekiq::Web, at: "/sidekiq"
    end

    resources :reviews
    resources :scholarships
    resources :discount_codes
    resources :bootcamps do
      member do
        put :publish
        put :unpublish
      end
    end
    resources :posts, except: :show do
      member do
        put :publish
        put :unpublish
      end
    end
    resources :pages, except: :show do
      member do
        put :publish
        put :unpublish
      end
    end
    resources :sponsors, except: :show
    resources :speakers, except: :show
    resources :students, except: :show
    resources :open_days, except: :show
    resources :orders, except: :show do
      member do
        patch :manually_paid
        patch :paid_by_creditcard
        patch :send_invoice
        patch :send_prework
      end
    end
    resources :users, :except => :show
  end
end

app/models/bootcamp.rb
class Bootcamp < ActiveRecord::Base
  attr_accessor :unpublish

  validates_presence_of :name, :level, :starts_at, :ends_at

  before_validation :set_unpublished, if: :should_unpublish?
  has_many :orders

  def self.published
    where(
      'published_at IS NOT NULL AND starts_at >= ? AND published_at <= ?',
      Date.today, Date.today
    )
  end

  def self.beginner
    where(level: 1)
  end

  def self.intermediate
    where(level: 2)
  end

  def self.advanced
    where(level: 3)
  end

  def self.frontend
    where(level: 99)
  end

  def self.by_date
    order(starts_at: :asc)
  end

  def beginner?
    level == 1
  end

  def readable_date_range
    "#{starts_at.day} #{starts_at.strftime("%b")}-#{ends_at.day} #{ends_at.strftime("%b")}, #{ends_at.year}"
  end

  def name_with_dates
    "#{name} - From #{starts_at.strftime("%b %d")} to #{ends_at.strftime("%b %d")}, #{ends_at.year}"
  end

  def level_name
    _level = LevelCollection.find(level)
    return "not set" if _level.blank?
    _level.name
  end

  def published?
    !unpublished?
  end

  def unpublished?
    published_at.nil? || published_at > Date.today
  end

  def publish!
    return true if published?
    update(published_at: Date.today)
  end

  def unpublish!
    return true if unpublished?
    update(published_at: nil)
  end

  def ticket_prices
    if Rails.env.test?
      {
          community: community_price,
          normal: normal_price,
          supporter: supporter_price,
      }
    else
      {
        normal: normal_price
      }
    end
  end

  def community_price
    read_attribute(:community_price) || 999
  end

  def normal_price
    read_attribute(:normal_price) || 1099
  end

  def supporter_price
    read_attribute(:supporter_price) || 1199
  end

  private

  def set_unpublished
    self.published_at = nil
  end

  def should_unpublish?
    unpublish.to_i > 0
  end
end

app/controllers/admin/bootcamps_controller.rb
class Admin::BootcampsController < Admin::AdminController
  before_action :set_bootcamp, only: [:show, :edit, :update, :destroy, :publish, :unpublish]

  respond_to :html

  def index
    @bootcamps = Bootcamp.where('ends_at > NOW()').order(starts_at: :asc)
    respond_with(@bootcamps)
  end

  def show
    respond_with(@bootcamp)
  end

  def new
    @bootcamp = Bootcamp.new
    respond_with(@bootcamp)
  end

  def edit
  end

  def create
    @bootcamp = Bootcamp.new(bootcamp_params)
    @bootcamp.save
    respond_with(:admin, @bootcamp)
  end

  def update
    @bootcamp.update(bootcamp_params)
    respond_with(:admin, @bootcamp)
  end

  def publish
    @bootcamp.publish!
    redirect_to action: :index
  end

  def unpublish
    @bootcamp.unpublish!
    redirect_to action: :index
  end

  def destroy
    @bootcamp.destroy
    respond_with(:admin, @bootcamp)
  end

  private
    def set_bootcamp
      @bootcamp = Bootcamp.find(params[:id])
    end

    def bootcamp_params
      params.require(:bootcamp).permit(:name, :starts_at, :ends_at, :location,
        :level, :community_price, :normal_price, :supporter_price, :published_at,
        :unpublish, :sold_out)
    end
end

app/views/admin/bootcamps/_form.html.slim
= form_for([:admin, @bootcamp], :html => { :class => "form-horizontal" }) do |f|
  - if @bootcamp.errors.any?
    .alert.alert-danger.alert-dismissable
      button.close type="button" data-dismiss="alert" aria-hidden="true"
        | &times;
      h4= "#{pluralize(@bootcamp.errors.count,"error")} prohibited this bootcamp from being saved:"
      ul
        - @bootcamp.errors.full_messages.each do |msg|
          li= msg
  .form-group
    = f.label :name, :class => "col-sm-2 control-label"
    .col-sm-10
      = f.text_field :name, :class => "form-control"
  .form-group
    = f.label :level, :class => "col-sm-2 control-label"
    .col-sm-10
      = f.collection_select :level, LevelCollection.all, :id, :name, prompt: true, :class => "form-control"
  .form-group
    = f.label :location, :class => "col-sm-2 control-label"
    .col-sm-10
      = f.text_field :location, :class => "form-control"
  .form-group
    = f.label :starts_at, :class => "col-sm-2 control-label"
    .col-sm-10
      = f.date_select :starts_at, :class => "form-control"
  .form-group
    = f.label :ends_at, :class => "col-sm-2 control-label"
    .col-sm-10
      = f.date_select :ends_at, :class => "form-control"
  .form-group
    = f.label :published_at, :class => "col-sm-2 control-label"
    .col-sm-10
      = f.date_select :published_at, :class => "form-control"
  .form-group
    = f.label :unpublish, :class => "col-sm-2 control-label"
    .col-sm-10
      = f.check_box :unpublish, :class => "form-control"
  .form-group
    = f.label :sold_out, :class => "col-sm-2 control-label"
    .col-sm-10
      = f.check_box :sold_out, :class => "form-control"
  .form-group
    = f.label :community_price, :class => "col-sm-2 control-label"
    .col-sm-10
      = f.number_field :community_price, :class => "form-control", placeholder: @bootcamp.community_price
  .form-group
    = f.label :normal_price, :class => "col-sm-2 control-label"
    .col-sm-10
      = f.number_field :normal_price, :class => "form-control", placeholder: @bootcamp.normal_price
  .form-group
    = f.label :supporter_price, :class => "col-sm-2 control-label"
    .col-sm-10
      = f.number_field :supporter_price, :class => "form-control", placeholder: @bootcamp.supporter_price
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit :class => "btn btn-primary"

app/views/admin/bootcamps/edit.html.slim
.page-header
  = link_to admin_bootcamps_path, :class => 'btn btn-default' do
    span.glyphicon.glyphicon-list-alt
    |  Back
  = link_to [:admin, @bootcamp], :class => 'btn btn-primary' do
    span.glyphicon.glyphicon-info-sign
    |  Show
  h1
    | Editing
    | bootcamp

= render 'form'

app/views/admin/bootcamps/index.html.slim
.page-header
  = link_to new_admin_bootcamp_path, :class => 'btn btn-primary' do
    span.glyphicon.glyphicon-plus
    |  New Bootcamp
  h1
    | Listing Bootcamps

.table-responsive
  table.table.table-striped.table-bordered.table-hover
    thead
      tr
        th
          | Name
        th
          | Location
        th
          | Starts At
        th
          | Ends At
        th
        th
        th
    tbody
      - @bootcamps.each do | bootcamp |
        tr
          td
            = "#{bootcamp.name} (#{bootcamp.level_name}#{bootcamp.sold_out? ? ', SOLD OUT' : ''})"
          td
            = bootcamp.location
          td
            = bootcamp.starts_at
          td
            = bootcamp.ends_at
          td
            = link_to 'Publish', publish_admin_bootcamp_path(bootcamp), method: :put if bootcamp.unpublished?
            = link_to 'Unpublish', unpublish_admin_bootcamp_path(bootcamp), method: :put if bootcamp.published?
          td
            = link_to 'Edit', edit_admin_bootcamp_path(bootcamp)
          td
            = link_to 'Destroy', [:admin, bootcamp], method: :delete, data: { confirm: 'Are you sure?' }

app/views/admin/bootcamps/new.html.slim
.page-header
  = link_to admin_bootcamps_path, :class => 'btn btn-default' do
    span.glyphicon.glyphicon-list-alt
    |  Back
  h1
    | New
    | bootcamp

= render 'form'

app/views/admin/bootcamps/show.html.slim
.page-header
  = link_to admin_bootcamps_path, :class => 'btn btn-default' do
    span.glyphicon.glyphicon-list-alt
    |  Back
  = link_to edit_admin_bootcamp_path(@bootcamp), :class => 'btn btn-primary' do
    span.glyphicon.glyphicon-pencil
    |  Edit
  h1
    | Show Bootcamp
dl.dl-horizontal
  dt
    | Name:
  dd
    = "#{@bootcamp.name} (#{@bootcamp.level_name})"
  dt
    | Location:
  dd
    = @bootcamp.location
  dt
    | Starts At:
  dd
    = @bootcamp.starts_at
  dt
    | Ends At:
  dd
    = @bootcamp.ends_at