config/routes.rb
Rails.application.routes.draw do
  localized do
    devise_for :users, :skip => [:registrations]

    as :user do
      get 'users/edit' => 'devise/registrations#edit', :as => :edit_user_registration
      put 'users/:id' => 'devise/registrations#update', :as => :user_registration
    end

    root to: "static_pages#home"

    get '/courses' => 'programs#index', as: :courses
    get '/courses/beginner-bootcamp' => 'programs#level_one', as: :courses_beginner_bootcamp
    get '/courses/intermediate-bootcamp' => 'programs#level_two', as: :courses_intermediate_bootcamp
    get '/courses/advanced-bootcamp' => 'programs#level_three', as: :courses_advanced_bootcamp
    get '/courses/frontend-bootcamp' => 'programs#frontend_bootcamp', as: :courses_frontend_bootcamp

    get '/enroll' => 'orders#new', as: :enroll
    get '/order/:id' => 'orders#show', as: :order
    get '/team' => 'static_pages#team', as: :team
    get '/contact' => 'static_pages#contact', as: :contact
    get '/newsletter' => 'static_pages#newsletter', as: :newsletter

    get '/code-of-conduct' => 'pages#show', id: 'code-of-conduct', as: :code_of_conduct
    get '/terms-and-conditions' => 'pages#show', id: 'terms-conditions', as: :terms_and_conditions
    get '/cancellation-policy' => 'pages#show', id: 'cancellation-policy', as: :cancellation_policy
    get '/faq' => 'pages#show', id: 'faq', as: :faq

    get '/open-evening' => 'static_pages#open_evening', as: :open_evening

    get '/students/:id/qr-code' => 'students#qr_code'
    get '/students/:id/check' => 'students#check_qr_code'

    get '/styleguide' => 'static_pages#styleguide'

    resources :scholarships, only: [:create] do
      collection do
        get :apply
        get :thanks
        get :redirect
      end
    end

    resources :blog, controller: 'posts', only: [:index, :show]
    resources :pages, only: [:show]
    resources :sponsors, only: [:index, :new, :create] do
      member do
        get :thanks
      end

      collection do
        get :plans
      end
    end

    resources :speakers, only: [:index, :new, :create] do
      member do
        get :thanks
      end
    end

    resources :enroll, controller: 'orders', only: [:create, :show] do
      collection do
        post :webhook
      end

      member do
        get :thanks
        post :stripe_webhook
        patch :stripe_token
      end
    end

    get '/sitemap.:format' => 'application#sitemap', constraints: { format: :xml }, as: :sitemap
  end

  namespace :admin do
    get '/' => 'admin#dashboard', as: :root

    require 'sidekiq/web'
    authenticate :user do
      mount Sidekiq::Web, at: "/sidekiq"
    end

    resources :reviews
    resources :scholarships
    resources :discount_codes
    resources :bootcamps do
      member do
        put :publish
        put :unpublish
      end
    end
    resources :posts, except: :show do
      member do
        put :publish
        put :unpublish
      end
    end
    resources :pages, except: :show do
      member do
        put :publish
        put :unpublish
      end
    end
    resources :sponsors, except: :show
    resources :speakers, except: :show
    resources :students, except: :show
    resources :open_days, except: :show
    resources :orders, except: :show do
      member do
        patch :manually_paid
        patch :paid_by_creditcard
        patch :send_invoice
        patch :send_prework
      end
    end
    resources :users, :except => :show
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::AdminController

  before_action :set_order, only: [:show, :edit, :update, :destroy, :manually_paid, :paid_by_creditcard, :send_invoice, :send_prework]

  respond_to :html

  def index
    @orders = Order.includes(:discount_code, :students, :bootcamp).
      order('bootcamps.starts_at desc, orders.created_at desc').
      page(page_number).per(10)

    respond_with(@orders)
  end

  def show
    respond_with(@order)
  end

  def edit
  end

  def update
    if @order.update(order_params)
      redirect_to admin_order_path(@order)
    else
      render 'edit'
    end
  end

  def destroy
    if @order && @order.destroy
      redirect_to admin_orders_path, notice: 'Order destroyed successfully.'
    else
      redirect_to admin_orders_path, error: 'Could not destroy order, please try again.'
    end
  end

  def manually_paid
    if @order.update(manually_paid: true)
      flash[:notice] = 'Status set to manually paid'
      send_invoice_and_tickets!
    else
      flash[:error] = 'Could not update status, try again'
    end
    redirect_to admin_orders_path
  end

  def paid_by_creditcard
    if @order.update(paid_by_creditcard: true)
      flash[:notice] = 'Status set to paid by creditcard'
      send_invoice_and_tickets!
    else
      flash[:error] = 'Could not update status, try again'
    end
    redirect_to admin_orders_path
  end

  def send_invoice
    if @order
      InvoiceMailWorker.perform_async(@order.id)
      redirect_to admin_orders_path, notice: 'Invoice queued for sending.'
    else
      redirect_to admin_orders_path, error: 'Could not find order, please try again.'
    end
  end

  def send_prework
    if @order
      PreworkMailWorker.perform_async(@order.id)
      redirect_to admin_orders_path, notice: 'Prework queued for sending.'
    else
      redirect_to admin_orders_path, error: 'Could not find order, please try again.'
    end
  end

  private ###########################################################################################

  def set_order
    @order = Order.find_by_identifier(params[:id])
  end

  def order_params
    params.require(:order).permit(:price, :paid_at, :mollie_payment_id, :refunded_at, :mollie_refund_id,
      :billing_name, :billing_email, :billing_address, :billing_postal, :billing_city, :billing_country,
      :billing_phone, :billing_company_name, :confirmed_at, :terms_and_conditions, :bootcamp_id,
      cart: [:community, :normal, :supporter],
      students_attributes: [:first_name, :last_name, :email, :twitter_handle, :github_handle, :birth_date, :remarks, :allergies, :owns_laptop])
  end

  def page_number
    (params[:page] || 1).to_i
  end

  def send_invoice_and_tickets!
    InvoiceMailWorker.perform_async(@order.id)
    TicketMailWorker.perform_async(@order.id)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:webhook, :stripe_webhook]

  before_filter :disable_sidebar

  before_action :set_order, only: [:show, :thanks, :stripe_token]

  respond_to :html

  def show
  end

  def new
    @bootcamps = Bootcamp.published.by_date
    reset_order_session!
    session[:order_params] ||= {}
    @order = Order.new(session[:order_params])
    @order.current_step = session[:order_step]
    @order.bootcamp = @bootcamps.first

    mixpanel.track '[visits] Order Page'
    track_discount_code!
  end

  def create
    @bootcamps = Bootcamp.published.by_date
    session[:order_params] ||= {}
    session[:order_params].deep_merge!(order_params) if order_params

    mixpanel.track 'Order Ticket', order_params

    @order = Order.new(session[:order_params])

    @order.current_step = session[:order_step]

    if params[:back_button]
      @order.previous_step
      build_students
      @order.valid?
    elsif @order.last_step?
      finish_up_after_confirmation
      @order.save
    elsif @order.validating_promo_code?
      @order.validate_discount_code
      @order.validate_promo_code = nil # reset
    elsif @order.selecting_bootcamp?
      @order.select_bootcamp = nil # reset
    else
      build_students
      @order.next_step if @order.valid?
    end

    session[:order_step] = @order.current_step

    if @order.persisted?
      flash[:notice] = "Thank you for your registration!"
      reset_order_session!
      enqueue_payment_email!
      @order.students.each { |student| add_to_list(student) }
      redirect_to order_url(@order)
    else
      render :new
    end
  end

  def webhook
    @order = Order.find_by_mollie_payment_id(params[:id])
    if @order.present?
      if @order.payment.present?
        payment_status = @order.payment.status
        if @order.payment.paid? && @order.mollie_status != 'paid'
          @order.update(paid_at: Time.now, mollie_status: payment_status)
          send_invoice_and_tickets!
        else
          @order.update(mollie_status: payment_status)
        end
      end
    end
  rescue Mollie::API::Exception => error
    Appsignal.add_exception error
    Rails.logger.info error.message
  ensure
    render text: 'OK'
  end

  def stripe_webhook
    if params[:object] == 'event'
      if params[:type] == 'charge.succeeded'
        @order.paid_at = Time.now
        @order.stripe_payload = params
        @order.save!
      end
    end
  end

  def thanks; end

  def stripe_token
    if params[:stripeToken].present?
      if @order.update(stripe_token: params[:stripeToken])
        enqueue_creditcard_charge!
        flash[:notice] = "Thank you for your registration!"
      else
        flash[:error] = "Sorry, your creditcard payment could not be processed, please contact us at support@developmentbootcamp.nl"
      end
    else
      flash[:error] = "Sorry, your creditcard payment could not be processed, please try again or contact us at support@developmentbootcamp.nl"
    end
    redirect_to enroll_url(@order)
  end

  protected #########################################################################################

  def orders_controller?
    true
  end

  private ###########################################################################################

  def set_order
    @order = Order.find_by_identifier(params[:id])
  end

  def order_params
    params.require(:order).permit(:price, :promo_code, :paid_at, :mollie_payment_id, :refunded_at, :mollie_refund_id,
      :billing_name, :billing_email, :billing_address, :billing_postal, :billing_city, :billing_country, :validate_promo_code,
      :billing_phone, :billing_company_name, :confirmed_at, :terms_and_conditions, :bootcamp_id, :select_bootcamp,
      cart: [:community, :normal, :supporter],
      students_attributes: [:first_name, :last_name, :email, :twitter_handle, :github_handle, :birth_date,
        :remarks, :allergies, :owns_laptop, :phone_number])
  end

  def add_to_list(student)
    gb = Gibbon::API.new
    gb.lists.subscribe({
      :id => MailingLists::STUDENTS,
      email: {
        email: student.email
      },
      merge_vars: {
        FNAME: student.first_name,
        LNAME: student.last_name
      }
    })
  rescue Gibbon::MailChimpError => e
    logger.error "Could not add #{student.email} to students mailing list: #{e.message}"
  end

  def build_students
    if @order.current_step =~ /^students/
      student_index = @order.current_step.split('-').last.to_i + 1
    else
      student_index = 0
    end
    amount_to_build = @order.cart_sum_tickets - @order.students.size
    amount_to_build.times { @order.students.build }
    students_to_take = @order.students.to_a.first(student_index)
    @order.students = []
    students_to_take.each do |student|
      @order.students << student
    end
  end

  def finish_up_after_confirmation
    @order.confirmed_at = Time.now
    @order.price = @order.cart_sum_total
  end

  def reset_order_session!
    session.delete(:order_step)
    session.delete(:order_params)
  end

  def send_invoice_and_tickets!
    InvoiceMailWorker.perform_async(@order.id)
    TicketMailWorker.perform_async(@order.id)
  end

  def enqueue_payment_email!
    FollowupMailWorker.perform_in(1.hour, @order.id)
  end

  def enqueue_creditcard_charge!
    CreditcardChargerWorker.perform_async(@order.id)
  end

  def track_discount_code!
    params[:promo] ||= 'Scholingsvoucher' if Date.today <= Date.parse('16-12-31') && !!!Rails.env.test? # TODO: cleanup!

    return unless params[:promo].present? || session[:discount_code_tracked].present?

    @order.promo_code = params[:promo] || session[:discount_code_tracked]
    @order.validate_discount_code
    return if @order.discount_code.blank?

    return if session[:discount_code_tracked] == @order.discount_code.code

    @order.discount_code.track_click!
    session[:discount_code_tracked] = @order.discount_code.code
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
  def payment_link_to(text, order, options = {})
    # We set the host and port here because Mollie does not accept local hosts.
    payment_options = { redirectUrl: thanks_enroll_url(order, host: Rails.application.config.hosts[I18n.locale]) }
    payment_options[:webhookUrl] = webhook_enroll_index_url(host: 'www.developmentbootcamp.nl')
    payment = order.create_payment payment_options
    link_to text, payment.getPaymentUrl, options
  end

  def order_step_name(step)
    if step =~ /^students/
      nr = step.split('-').last.to_i + 1
      "Student Details #{nr}"
    elsif step == 'tickets'
      "Choose Tickets"
    elsif step == 'details'
      "Billing Information"
    elsif step == 'confirmation'
      "Confirmation"
    end
  end

  def order_step_icon(step)
    if step =~ /^students/
      fa_icon 'user fw'
    elsif step == 'tickets'
      fa_icon 'ticket fw'
    elsif step == 'details'
      fa_icon 'globe fw'
    elsif step == 'confirmation'
      fa_icon 'check fw'
    end
  end
end

app/views/admin/orders/_cart.html.slim
h3 Tickets
- @order.cart.each do |ticket, amount|
  - next unless amount.present?
  p = "#{ticket.humanize} Tickets: #{amount}"

app/views/admin/orders/_form.html.slim
h2 Billing Details

= bootstrap_form_for [:admin, @order] do |f|
  = f.text_field :billing_name, label: 'Full name'
  = f.text_field :billing_company_name, required: false, label: 'Company name'
  = f.text_field :billing_email
  = f.text_field :billing_address
  = f.text_field :billing_postal
  = f.text_field :billing_city
  = f.country_select :billing_country, priority_countries: ['NL', 'DE', 'BE', 'GB']
  = f.text_field :billing_phone
  = f.select :bootcamp_id, Bootcamp.by_date.map{|b| [b.name_with_dates, b.id] }
  = f.check_box :terms_and_conditions
  = f.primary

app/views/admin/orders/_students.html.slim
h3 Students
- @order.students.each do |student|
  .row
    .col-md-12
      h4 = student.full_name
    .col-md-2
      .img-responsive= image_tag student.gravatar_url
    .col-md-10
      p = link_to "https://secure.helpscout.net/mailbox/cc832e3adfe530e1/new-ticket/522398/?email=#{student.email}&name=#{student.full_name}&phone=#{student.phone_number}" do
        => fa_icon 'envelope'
        | Email
      p = link_to edit_admin_student_path(student) do
        = "#{student.first_name} #{student.last_name}"

app/views/admin/orders/edit.html.slim
= render 'form'
= render 'cart'
= render 'students'

app/views/admin/orders/index.html.slim
.order.col-md-12
  h1 Orders
  .pull-right= link_to 'Add new order', enroll_path,
    class: 'btn btn-primary'

- @orders.each do |order|
  .order.col-md-12
    h3.bg-info
      = link_to edit_admin_order_path(order) do
        = order.billing_name
    p
      - if order.bootcamp.present?
        span.label.label-info
          => fa_icon 'graduation-cap'
          => order.bootcamp.name_with_dates
          - bootcamp_counts ||= {}
          - bootcamp_counts[order.bootcamp.id] ||= order.bootcamp.orders.count
          = "(#{bootcamp_counts[order.bootcamp.id]})"
      span.pull-right
        =<> link_to send_invoice_admin_order_path(order), method: :patch, class: 'btn btn-small' do
          => fa_icon 'envelope'
          = 'Send invoice'
        - if order.bootcamp && order.bootcamp.beginner?
         =<> link_to send_prework_admin_order_path(order), method: :patch, class: 'btn btn-small' do
            => fa_icon 'envelope'
            = 'Send prework'
        - if order.paid?
          span.label.label-success =<> 'Paid'
          - if order.discount_code.present?
            span.label.label-warning = "#{order.discount_code.code} (#{order.discount_code.discount_percentage}%)"
        - elsif order.payment
          span.label.label-warning =< order.payment.status
        - unless order.paid?
          =<> link_to 'Manually Paid', manually_paid_admin_order_path(order), method: :patch, class: 'btn btn-small'
          - if order.discount_code.present?
            span.label.label-warning = "#{order.discount_code.code} (#{order.discount_code.discount_percentage}%)"
          / = link_to 'Payment link', enroll_url(order), class: 'btn btn-small'
    - order.students.each do |student|
      .col-md-10
        .col-md-2
          .img-responsive= image_tag student.gravatar_url
        .col-md-10
          p = link_to "https://secure.helpscout.net/mailbox/cc832e3adfe530e1/new-ticket/522398/?email=#{student.email}&name=#{student.full_name}&phone=#{student.phone_number}" do
            => fa_icon 'envelope'
            | Email
          p = link_to edit_admin_student_path(student) do
            = "#{student.first_name} #{student.last_name}"
          h4 Remarks
          p.bg-info= student.remarks
          h4 Dietary Wishes
          p.bg-warning= student.allergies
          p.pull-right= student.created_at.to_s(:long)
    .col-md-2
      p= link_to 'Edit', edit_admin_order_path(order)
      p= link_to 'Delete', admin_order_path(order), method: :delete,
        data: { confirm: 'Are you sure you want to delete this order?' }

.text-center= paginate @orders