config/routes.rb
Rails.application.routes.draw do
  localized do
    devise_for :users, :skip => [:registrations]

    as :user do
      get 'users/edit' => 'devise/registrations#edit', :as => :edit_user_registration
      put 'users/:id' => 'devise/registrations#update', :as => :user_registration
    end

    root to: "static_pages#home"

    get '/courses' => 'programs#index', as: :courses
    get '/courses/beginner-bootcamp' => 'programs#level_one', as: :courses_beginner_bootcamp
    get '/courses/intermediate-bootcamp' => 'programs#level_two', as: :courses_intermediate_bootcamp
    get '/courses/advanced-bootcamp' => 'programs#level_three', as: :courses_advanced_bootcamp
    get '/courses/frontend-bootcamp' => 'programs#frontend_bootcamp', as: :courses_frontend_bootcamp

    get '/enroll' => 'orders#new', as: :enroll
    get '/order/:id' => 'orders#show', as: :order
    get '/team' => 'static_pages#team', as: :team
    get '/contact' => 'static_pages#contact', as: :contact
    get '/newsletter' => 'static_pages#newsletter', as: :newsletter

    get '/code-of-conduct' => 'pages#show', id: 'code-of-conduct', as: :code_of_conduct
    get '/terms-and-conditions' => 'pages#show', id: 'terms-conditions', as: :terms_and_conditions
    get '/cancellation-policy' => 'pages#show', id: 'cancellation-policy', as: :cancellation_policy
    get '/faq' => 'pages#show', id: 'faq', as: :faq

    get '/open-evening' => 'static_pages#open_evening', as: :open_evening

    get '/students/:id/qr-code' => 'students#qr_code'
    get '/students/:id/check' => 'students#check_qr_code'

    get '/styleguide' => 'static_pages#styleguide'

    resources :scholarships, only: [:create] do
      collection do
        get :apply
        get :thanks
        get :redirect
      end
    end

    resources :blog, controller: 'posts', only: [:index, :show]
    resources :pages, only: [:show]
    resources :sponsors, only: [:index, :new, :create] do
      member do
        get :thanks
      end

      collection do
        get :plans
      end
    end

    resources :speakers, only: [:index, :new, :create] do
      member do
        get :thanks
      end
    end

    resources :enroll, controller: 'orders', only: [:create, :show] do
      collection do
        post :webhook
      end

      member do
        get :thanks
        post :stripe_webhook
        patch :stripe_token
      end
    end

    get '/sitemap.:format' => 'application#sitemap', constraints: { format: :xml }, as: :sitemap
  end

  namespace :admin do
    get '/' => 'admin#dashboard', as: :root

    require 'sidekiq/web'
    authenticate :user do
      mount Sidekiq::Web, at: "/sidekiq"
    end

    resources :reviews
    resources :scholarships
    resources :discount_codes
    resources :bootcamps do
      member do
        put :publish
        put :unpublish
      end
    end
    resources :posts, except: :show do
      member do
        put :publish
        put :unpublish
      end
    end
    resources :pages, except: :show do
      member do
        put :publish
        put :unpublish
      end
    end
    resources :sponsors, except: :show
    resources :speakers, except: :show
    resources :students, except: :show
    resources :open_days, except: :show
    resources :orders, except: :show do
      member do
        patch :manually_paid
        patch :paid_by_creditcard
        patch :send_invoice
        patch :send_prework
      end
    end
    resources :users, :except => :show
  end
end

app/views/shared/_admin_navigation.html.slim
nav.navbar.navbar-inverse.navbar-fixed-top
  .container-fluid
    .navbar-header
      button.navbar-toggle type='button' data-toggle='collapse' data-target='.navbar-collapse'
        span.sr-only
          | Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to admin_root_path, :class => 'navbar-brand' do
        = fa_icon "line-chart fw"
        | DBC
    #admin-navbar.collapse.navbar-collapse
      ul.nav.navbar-nav
        = menu_item_for admin_orders_path do
          = fa_icon 'heart fw'
          | Orders
          span.badge =< Order.count
        = menu_dropdown_for 'Content' do
          = menu_item_for admin_posts_path do
            = fa_icon 'edit fw'
            | Blog
          = menu_item_for admin_pages_path do
            = fa_icon 'bookmark fw'
            | Pages
          = menu_item_for admin_reviews_path do
            = fa_icon 'star fw'
            | Reviews
        = menu_item_for admin_bootcamps_path do
          = fa_icon 'mortar-board fw'
          | Bootcamps
        = menu_dropdown_for 'Marketing' do
          = menu_item_for admin_open_days_path do
            = fa_icon 'heart fw'
            | Open Evenings
          = menu_item_for admin_sponsors_path do
            = fa_icon 'heart fw'
            | Sponsors
          = menu_item_for admin_discount_codes_path do
            = fa_icon 'heart fw'
            | Promo codes
        = menu_dropdown_for 'People' do
          = menu_item_for admin_users_path do
            = fa_icon 'users fw'
            | Team
          = menu_item_for admin_students_path do
            = fa_icon 'mortar-board fw'
            | Students
          = menu_item_for admin_scholarships_path do
            = fa_icon 'mortar-board fw'
            | Scholarships
          = menu_item_for admin_speakers_path do
            = fa_icon 'bullhorn fw'
            | Speakers
        = menu_item_for root_path do
          = fa_icon 'desktop fw'
        = menu_item_for edit_user_registration_path do
          = fa_icon 'user fw'

app/views/shared/_day_at_bootcamp.html.slim
.dbc-day-at#day-structure
  .inner.centered
    .block-title
      h2
        | A Day at our Bootcamp
        span We will keep you busy!

  .inner.justified
    p In the morning we start at 9:30am with a classroom lecture, followed by workshops until 5:30pm. We will pause only for lunch, coffee, and tea.
    p During the evenings we will have various cool keynotes and presentations on lighter subjects between 5:30pm and 7pm.

  .inner
    .dbc-daypart.part-one
      .time
        | 9:00 AM
      .activity
        h2 Daily keynote
        p by a great speaker
      .image

    .dbc-daypart.part-two
      .time
        | 10.30 AM
      .activity
        h2 Morning workshop sessions
        p individual practicing
      .image

    .dbc-daypart.part-three
      .time
        | 12.30 PM
      .activity
        h2 Lunch
        p included
      .image

    .dbc-daypart.part-four
      .time
        | 1:30 PM
      .activity
        h2 Afternoon workshop sessions
        p in small teams
      .image

    .dbc-daypart.part-five
      .time
        | 5:00 PM
      .activity
        h2 Evening break
      .image

    .dbc-daypart.part-six
      .time
        | 5:30 - 7:00 PM
      .activity
        h2 Evening Sessions
        p Inspiring stuff!
      .image

  .inner.centered
    p Other activities: Party, Hackathon, Contest

app/views/shared/_flash_messages.html.slim
- flash.each do |name, msg|
  div class="alert alert-#{ name == 'alert' ? "danger" : "success" } alert-dismissable"
    button.close type='button' data-dismiss='alert' aria-hidden='true'
      | &times;
    = msg

app/views/shared/_footer.html.slim
- localized_cache ['footer', Time.now.year] do
  footer.page-footer
    .container
      .row
        .col.s12.m4
          img.responsive-img src="codaisseur.png" /
          ul
            li = link_to "Home", root_path
            li = link_to "Cursussen", courses_path
            li = link_to "Aanmelden", enroll_path
            li = link_to "Support",contact_path
            li = link_to "Team", team_path
            li = link_to "Traineeship", href="https://www.facebook.com/developmentbootcamp"
        .col.s12.m4
          h5.white-text Development Bootcamp
          p.white-text
            | Codaisseur BV
            br/
            | info@codaisseur.com
            br/
            | Weesperstraat 61
            br/
            | 1018 VN Amsterdam
            br/
            | The Netherlands
            br/
          p.white-text
            | Tel: +31202615197Z
            br/
            | KvK: 63359359
            br/
            | VAT ID: NL855202907B01
            br/
            | Bank: NL90ABNA0401849279
            br/
        .col.s12.m4
          h5.white-text Follow us
          = link_to href="https://twitter.com/codaisseur" do
            i.span.fa-stack.fa-lg
              i.fa.fa-circle-thin.fa-stack-2x.fa
              i.fa.fa-twitter.fa-stack-2
          = link_to href="https://www.facebook.com/developmentbootcamp" do
            i.span.fa-stack.fa-lg
              i.fa.fa-circle-thin.fa-stack-2x.fa
              i.fa.fa-facebook.fa-stack-2
          = link_to href="https://www.linkedin.com/company/development-bootcamp" do
            i.span.fa-stack.fa-lg
              i.fa.fa-circle-thin.fa-stack-2x.fa
              i.fa.fa-linkedin.fa-stack-2
          = link_to href="https://github.com/devbootcamps" do
            i.span.fa-stack.fa-lg
              i.fa.fa-circle-thin.fa-stack-2x.fa
              i.fa.fa-github.fa-stack-2
          .row
            .input-field.col.s8
              h3.white-text  Subscribe to our newsletter
              input#email.white-text placeholder=("Enter your email adres") type="text" /
              button.btn.waves-effect.waves-light name="action" type="submit"
                | Submit
                i.material-icons.right send
    /! Scripts
    script src="https://code.jquery.com/jquery-2.1.1.min.js"
    script src="js/materialize.js"
    script src="js/init.js"

app/views/shared/_menu_items.html.slim
- localized_cache ["menu-items/#{request.path}"] do
  = menu_item_for root_url, active: request.path == root_path do
    => fa_icon 'home'
    = t(:nav_home)
  = menu_item_for courses_path do
    => fa_icon 'graduation-cap'
    = t(:nav_courses)
  = menu_item_for enroll_path do
    => fa_icon 'ticket'
    = t(:nav_enroll)
  = menu_item_for contact_path do
    = t(:nav_support)

app/views/shared/_navigation.html.slim
nav.navbar.navbar-default.navbar-fixed-top role="navigation"
  .inner
    .navbar-header
      button.navbar-toggle.collapsed data-target="#navbar-collapse" data-toggle="collapse" type="button"
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to root_path, class: "navbar-brand"
        | Development Bootcamp

    #navbar-collapse.collapse.navbar-collapse
      ul.nav.navbar-nav
        = menu_item_for courses_path do
          = t(:nav_courses)
        = menu_item_for enroll_path do
          => t(:nav_enroll)
        = menu_item_for apply_scholarships_path do
          = t(:nav_scholarships)
        = menu_item_for blog_index_path do
          = t(:nav_blog)
        = menu_item_for contact_path do
          = t(:nav_support)

      ul.nav.navbar-nav.navbar-right.language-switcher
        li.language = link_to 'EN', root_en_url(host: Rails.application.config.hosts[:en]), hreflang: :en, class: :en unless I18n.locale == :en
        li.language = link_to 'NL', root_nl_url(host: Rails.application.config.hosts[:nl]), hreflang: :nl, class: :nl unless I18n.locale == :nl

app/views/shared/_newsletter_form.html.slim
- localized_cache ['newsletter-form'] do
  .dbc-container
    .inner
      form#mc-embedded-subscribe-form.validate action="//developmentbootcamp.us9.list-manage.com/subscribe/post?u=f107d6a3948661d72e4628ba1&amp;id=aff9cced90" method="post" name="mc-embedded-subscribe-form" novalidate="" target="_blank"
        h2 = t('.title')
        .form-group
          label for="mce-FNAME" = t('.first_name')
          input#mce-FNAME.form-control name="FNAME" type="text" value="" /
        .form-group
          label for="mce-LNAME" = t('.last_name')
          input#mce-LNAME.form-control name="LNAME" type="text" value="" /
        .form-group
          label for="mce-EMAIL"
            = t('.email')
            span.asterisk *
          input#mce-EMAIL.required.email.form-control name="EMAIL" type="email" value="" /
        /! real people should not fill this in and expect good things - do not remove this or risk form bot signups
        div style=("position: absolute; left: -5000px;")
          input name="b_f107d6a3948661d72e4628ba1_aff9cced90" tabindex="-1" type="text" value="" /
        .clear
          input#mc-embedded-subscribe.button.primary name="subscribe" type="submit" value="Subscribe" /
          p
            em = t('.form_hint')

app/views/shared/_sidebar.html.slim
.dbc-sidebar
  nav
    ul
      = render 'shared/menu_items'

app/views/shared/_subnav.html.slim
- if @nav_items.any?
  nav.subnav
    ul
      - @nav_items.each do |label, link|
        = menu_item_for link, active: request.path == url_for(link) do
          = label

app/views/shared/_support.html.slim
#support
  = link_to '/pages/faq' do
    => fa_icon 'support fw'
    | FAQ